config/routes.rb
SchedulerApp::Application.routes.draw do

root :to => 'programs#index'

resources :users, :programs, :campuses, :cohorts, :classrooms, :bookings, :courses, :enrollments, :teaching_assignments
 


get "/login", to: 'sessions#new', as: "login"
delete "/logout", to: "sessions#destroy", as: "logout"

resources :sessions, only: [:new, :create, :destroy]

end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :courses
  has_many :cohorts, through: :courses
  has_many :campuses
  has_many :classrooms, through: :campuses
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])
    authorize! :show, @program

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    authorize! :new, @program

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
    authorize! :edit, @program
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])
    authorize! :create, @program

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])
    authorize! :update, @program

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy
    authorize! :destroy, @program

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  
<div class="container"> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Programs</h1>
 <h2>Select Program for Details</h2>
</div class="container">

<div class="container">  
 <table>
    <% @programs.each do |program| %>
  <tr>
    <td><%= link_to program.name, program if can? :show , program %></td>
    <td><%= link_to 'Edit', edit_program_path(program) if can? :edit , program %></td>
    <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy , program %></td><% end %>
  </tr>
</table>
<% if can? :create , Program %>
<%= link_to 'Add New Program...', new_program_path %>
<% end %>
</div>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <b>Name: </b>
  <%= @program.name %>
  <b>Description: </b>
  <%= @program.description %>
</p>

<%= link_to 'Back', programs_path %>
</div>