config/routes.rb
SchedulerApp::Application.routes.draw do

root :to => 'programs#index'

resources :users, :programs, :campuses, :cohorts, :classrooms, :bookings, :courses, :enrollments, :teaching_assignments
 


get "/login", to: 'sessions#new', as: "login"
delete "/logout", to: "sessions#destroy", as: "logout"

resources :sessions, only: [:new, :create, :destroy]

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :cohort
  belongs_to :student, class_name: "User", foreign_key: "student_id"
  attr_accessible :paid, :pre_work_completed, :cohort, :cohort_id, :student, :student_id
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enrollments }
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
    @enrollment = Enrollment.find(params[:id])

    authorize! :show, @enrollment

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enrollment }
    end
  end

  # GET /enrollments/new
  # GET /enrollments/new.json
  def new
    @enrollment = Enrollment.new
    @users = User.where(:role => 'student')

    authorize! :new, @enrollment

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enrollment }
    end
  end

  # GET /enrollments/1/edit
  def edit
    @enrollment = Enrollment.find(params[:id])
    @users = User.where(:role => 'student')

    authorize! :edit, @enrollment
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(params[:enrollment])
    @users = User.where(:role => 'student')

    authorize! :create, @enrollment

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'enrollment successfully created.' }
        format.json { render json: @enrollment, status: :created, location: @enrollment }
      else
        format.html { render action: "new" }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enrollments/1
  # PUT /enrollments/1.json
  def update
    @enrollment = Enrollment.find(params[:id])
    @users = User.where(:role => 'student')

    authorize! :update, @enrollment

    respond_to do |format|
      if @enrollment.update_attributes(params[:enrollment])
        format.html { redirect_to @enrollment, notice: 'enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment = Enrollment.find(params[:id])
    @enrollment.destroy

    authorize! :destroy, @enrollment

    respond_to do |format|
      format.html { redirect_to enrollments_url }
      format.json { head :no_content }
    end
  end
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
 <div class="container">
  <div class="field">
    <%= f.label :student  %>
    <%= f.select :student_id, options_from_collection_for_select(@users, "id", "name") %>
  </div>
  <div class="field">
    <%= f.label :cohort %>
    <%= f.select :cohort_id, options_from_collection_for_select(Cohort.all, "id", "name") %>
  </div>
  <div class="field">
    <%= f.label :pre_work_completed %>
    <%= f.select :pre_work_completed, ['True', 'False'] %>
  </div>
  <div class="field">
    <%= f.label :paid %>
    <%= f.number_field :paid %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Enrollments</h1>
<div class="container">
<table>  
<% @enrollments.each do |enrollment| %>
<tr>
  <td>Assignment <%= enrollment.id %>: </td><td>
  <td>  Assigning  <%= enrollment.student.name %></td>
  <td>to <%=    enrollment.cohort.name %></td>
  <td><%= link_to 'Show', enrollment if can? :show , enrollment %></td>
  <td><%= link_to 'Edit', edit_enrollment_path(enrollment) if can? :edit , enrollment %></td>
  <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy , enrollment %></td>
  </tr>
<% end %>
</table>
<br><br><br>

<% if can? :create , Enrollment %>
<%= link_to 'Add new enrollment...', new_enrollment_path %>
<% end %>
</div>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <b>Name: </b>
  <%= @enrollment.student.name %>
  <b>Cohort: </b>
  <%= @enrollment.cohort.name %>
</p>

<%= link_to 'Back', enrollments_path %>
</div>